#!/bin/bash
#0) find an article which provides an SRP or another accession for the SRA database, create the corresponding directory on the server

#1) input the SRP accession as the first argument of the script

#2) find all SRRs of this project
esearch -db sra -query $1 | efetch -format runinfo > annotation_$1.csv
#annotation_$1.csv is the annotation table that you can use later on
#scp stantikhonov@globe.autosome.ru:~/agingsignature/PRJNA281127/annotation_PRJNA281127.csv ~/Documents/
#you can view the annotation with the above command

#3) extract SRRs from the table (they are in the first column, hence “print $1”)
# In case you need to filter sth out first (here I filtered out ChIP-Seq):
#awk -F "\"*,\"*" '(NR == 1) || ($13 == "RNA-Seq")' annotation_$1.csv | awk -F "\"*,\"*" '{print $1}' | tail -n +2 > SRRlist.txt
#awk -F "\"*,\"*" '(NR == 1) || ($13 == "RNA-Seq")' annotation_$1.csv > annotation_$1.csv
awk -F "\"*,\"*" '$1 ~ /SRR/ {print $1}' annotation_$1.csv > SRRlist.txt

#4) download all of the fastq files for the given SRP in a tmux session
mkdir sras
cd sras
prefetch --option-file ../SRRlist.txt
cd ../
mkdir fastq.raw
cd fastq.raw
fastq-dump --split-files --gzip ../sras/*.sra
#fastq-dump --split-files --gzip $(cat ../SRRlist.txt)
#rm ../SRRlist.txt
cd ../

#5) run fastqc on all of the fastq files
mkdir fastqc.results
find ./ -maxdepth 1 -type f -exec bash -c 'bn=$(basename {}); bn1=${bn%.*}; zcat {} | fastqc stdin:$bn1 -o fastqc.results' \; > fastqc.results/fastqc.log
